"""Merge AkShare company financial report CSVs into a concise summary table.

The script expects the raw CSV files generated by
`src.data.stock.financial_reports`:

- balance_sheet.csv
- income_statement.csv
- cash_flow.csv
- financial_abstract.csv

It creates one row per report date and keeps a compact set of high-value metrics
from the three statements plus the "常用指标" section in financial_abstract.

Example:
    python -m src.data.stock.merge_reports \
        --input-dir output/stock/financial_reports/SZ000858 \
        --output output/stock/financial_reports/SZ000858/summary.csv
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


SUMMARY_METRICS = [
    "归母净利润",
    "营业总收入",
    "营业成本",
    "净利润",
    "扣非净利润",
    "股东权益合计(净资产)",
    "经营现金流量净额",
    "基本每股收益",
    "每股净资产",
    "每股现金流",
    "净资产收益率(ROE)",
    "总资产报酬率(ROA)",
    "毛利率",
    "销售净利率",
    "期间费用率",
    "资产负债率",
]

BALANCE_FIELDS = {
    "TOTAL_ASSETS": "总资产",
    "TOTAL_LIABILITIES": "总负债",
    "TOTAL_EQUITY": "所有者权益",
    "TOTAL_CURRENT_ASSETS": "流动资产合计",
    "TOTAL_CURRENT_LIAB": "流动负债合计",
    "INVENTORY": "存货",
    "ACCOUNTS_RECE": "应收账款",
    "SHORT_LOAN": "短期借款",
    "LONG_LOAN": "长期借款",
}

INCOME_FIELDS = {
    "TOTAL_OPERATE_INCOME": "营业总收入_报表",
    "OPERATE_INCOME": "营业收入_报表",
    "TOTAL_OPERATE_COST": "营业总成本",
    "OPERATE_COST": "营业成本_报表",
    "OPERATE_PROFIT": "营业利润",
    "TOTAL_PROFIT": "利润总额",
    "PARENT_NETPROFIT": "归母净利润_报表",
    "DEDUCT_PARENT_NETPROFIT": "扣非净利润_报表",
    "BASIC_EPS": "基本每股收益_报表",
    "DILUTED_EPS": "稀释每股收益",
}

CASH_FIELDS = {
    "NETCASH_OPERATE": "经营活动现金流量净额_报表",
    "NETCASH_INVEST": "投资活动现金流量净额",
    "NETCASH_FINANCE": "筹资活动现金流量净额",
    "END_CASH_EQUIVALENTS": "期末现金及现金等价物余额",
    "END_CASH": "期末现金余额",
}


def _read_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"missing file: {path}")
    return pd.read_csv(path)


def _normalize_report_date(series: pd.Series) -> pd.Series:
    return pd.to_datetime(series, errors="coerce").dt.strftime("%Y-%m-%d")


def _select_columns(df: pd.DataFrame, mapping: dict[str, str]) -> pd.DataFrame:
    cols = [c for c in mapping if c in df.columns]
    out = df[["REPORT_DATE", *cols]].copy()
    out["REPORT_DATE"] = _normalize_report_date(out["REPORT_DATE"])
    out = out.rename(columns=mapping)
    return out


def _build_abstract_summary(df: pd.DataFrame) -> pd.DataFrame:
    if not {"选项", "指标"}.issubset(df.columns):
        raise ValueError("financial_abstract.csv missing required columns: 选项, 指标")

    common = df[df["选项"] == "常用指标"].copy()
    if common.empty:
        common = df.copy()

    value_cols = [c for c in common.columns if c.isdigit() and len(c) == 8]
    if not value_cols:
        raise ValueError("financial_abstract.csv does not contain date columns")

    melted = common.melt(
        id_vars=["指标"],
        value_vars=value_cols,
        var_name="REPORT_KEY",
        value_name="value",
    )
    melted = melted[melted["指标"].isin(SUMMARY_METRICS)].copy()
    melted["REPORT_DATE"] = pd.to_datetime(melted["REPORT_KEY"], format="%Y%m%d", errors="coerce").dt.strftime("%Y-%m-%d")

    pivot = (
        melted.pivot_table(index="REPORT_DATE", columns="指标", values="value", aggfunc="first")
        .reset_index()
        .sort_values("REPORT_DATE", ascending=False)
    )
    pivot.columns.name = None
    return pivot


def build_summary(input_dir: Path) -> pd.DataFrame:
    balance = _read_csv(input_dir / "balance_sheet.csv")
    income = _read_csv(input_dir / "income_statement.csv")
    cash = _read_csv(input_dir / "cash_flow.csv")
    abstract = _read_csv(input_dir / "financial_abstract.csv")

    base_cols = [
        "SECURITY_CODE",
        "SECURITY_NAME_ABBR",
        "REPORT_DATE",
        "REPORT_TYPE",
        "REPORT_DATE_NAME",
        "NOTICE_DATE",
        "UPDATE_DATE",
    ]

    base = balance[base_cols].copy()
    base["REPORT_DATE"] = _normalize_report_date(base["REPORT_DATE"])
    base["NOTICE_DATE"] = _normalize_report_date(base["NOTICE_DATE"])
    base["UPDATE_DATE"] = _normalize_report_date(base["UPDATE_DATE"])

    balance_sel = _select_columns(balance, BALANCE_FIELDS)
    income_sel = _select_columns(income, INCOME_FIELDS)
    cash_sel = _select_columns(cash, CASH_FIELDS)
    abstract_sel = _build_abstract_summary(abstract)

    summary = base.merge(balance_sel, on="REPORT_DATE", how="left")
    summary = summary.merge(income_sel, on="REPORT_DATE", how="left")
    summary = summary.merge(cash_sel, on="REPORT_DATE", how="left")
    summary = summary.merge(abstract_sel, on="REPORT_DATE", how="left")

    summary = summary.sort_values("REPORT_DATE", ascending=False).reset_index(drop=True)
    return summary


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Merge company financial report CSVs into a summary table")
    parser.add_argument(
        "--input-dir",
        required=True,
        help="Directory containing balance_sheet.csv, income_statement.csv, cash_flow.csv, financial_abstract.csv",
    )
    parser.add_argument(
        "--output",
        required=True,
        help="Path to the summary CSV to generate",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    input_dir = Path(args.input_dir)
    output_path = Path(args.output)

    summary = build_summary(input_dir)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    summary.to_csv(output_path, index=False, encoding="utf-8-sig")
    print(f"[saved] {output_path} rows={len(summary)} cols={len(summary.columns)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


